{{- if .Values.global.security.enabled }}
{{- $istio_namespace := .Values.global.namespace }}
{{- $ca_hub := .Values.global.security.hub }}
{{- $ca_tag := .Values.global.security.tag }}
################################
# istio-CA cluster-wide
################################
# Service account CA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ca-service-account
  namespace: {{ $istio_namespace }}
---
# istio CA watching all namespaces
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: istio-ca
  namespace: {{ $istio_namespace }}
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        istio: istio-ca
    spec:
      serviceAccountName: istio-ca-service-account
      containers:
      - name: istio-ca
        image: {{$ca_hub}}/istio-ca:{{$ca_tag}}
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/bin/istio_ca"]
        args:
          - --grpc-port=8060
          - --grpc-hostname=istio-ca
          - --self-signed-ca=true
---
{{- end }}
